### PR TITLE
Add support for runtime arguments

### PR DESCRIPTION
**Pull request by lime008**
Adds support for providing runtime arguments for the built binary.

Fixes: #125
Could be used with #136 to also load arguments from the configuration.

### CODE REVIEW

**Comment by lime008** [comment]
The CodeCov upload failed but the actuall build is passing just for your info :)

**Comment by hnlq715** [comment]
Any updates?

**Comment by xiantang** [comment]
I will take a look for this ticket.

**Comment by credondocr** [comment]
Any updates?  I really need this feature! Thanks

**Comment by dlsrb6342** [comment]
@xiantang 
Any updates..?? This would be a nice feature.

**Comment by xiantang** [comment]
> @xiantang Any updates..?? This would be a nice feature.

I'll take a look in weekend.

**Comment by lime008** [comment]
I could fix the PR so that it doesn't have any merge conflicts.

**Comment by xiantang** [comment]
> I could fix the PR so that it doesn't have any merge conflicts.

go go go

**Comment by xiantang** [comment]
@lime008  any update?

**Comment by lime008** [comment]
Don't merge this yet there's a few bugs still. I'll fix them and notify you. @xiantang

**Comment by lime008** [comment]
This should work now.

**Review by xiantang — APPROVED** [review]

**Comment by xiantang** [comment]
LGTM

**Pull request merged**
